/*
  Auto-generated by Spline
*/
import React from "react";
import useSpline from "@splinetool/r3f-spline";

const logo = React.forwardRef((props, ref) => {
  const { nodes, materials } = useSpline(
    "https://prod.spline.design/0t3muY4YysS7NPtt/scene.splinecode"
  );
  return (
    <>
      <group
        name="Group"
        position={[-100, -10, 3.37]}
        rotation={[-Math.PI / 6, Math.PI / 5, Math.PI / 10]}
        ref={ref}
        scale={[0.1, 0.09, 0.09]}
      >
        <mesh
          name="Ellipse 3"
          geometry={nodes["Ellipse 3"].geometry}
          material={materials["Ellipse 3 Material"]}
          castShadow
          receiveShadow
          position={[-0.49, -0.12, -4.72]}
          rotation={[-Math.PI, 0, Math.PI]}
        />
        <mesh
          name="Ellipse 2"
          geometry={nodes["Ellipse 2"].geometry}
          material={materials["Ellipse 2 Material"]}
          castShadow
          receiveShadow
          position={[-0.72, -0.12, 4.4]}
        />
        <mesh
          name="Ellipse"
          geometry={nodes.Ellipse.geometry}
          material={materials["Ellipse Material"]}
          castShadow
          receiveShadow
          position={[0, 0, -3.37]}
        />
      </group>
    </>
  );
});
export default logo;
