/*
  Auto-generated by Spline
*/

import useSpline from "@splinetool/r3f-spline";

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline(
    "https://prod.spline.design/loneq18opX8tdwug/scene.splinecode"
  );
  return (
    <>
      <color attach="background" args={["#4b4d52"]} />
      <group {...props} dispose={null}>
        <group
          name="Frame"
          position={[-98.04, 427.06, -300.26]}
          rotation={[1.41, 0.09, -0.52]}
        >
          <mesh
            name="Cube 17"
            geometry={nodes["Cube 17"].geometry}
            material={materials["Cube 17 Material"]}
            castShadow
            receiveShadow
            position={[0, 0.47, 0]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.59, 0.81, 0.04]}
          />
          <mesh
            name="Cube 16"
            geometry={nodes["Cube 16"].geometry}
            material={materials.industrial}
            castShadow
            receiveShadow
            position={[0, -0.29, 0]}
            rotation={[Math.PI / 2, 0, -Math.PI]}
            scale={[0.73, 1, 0.05]}
          />
        </group>
        <group
          name="Coffee Cup"
          position={[-133.5, 426.16, -288.14]}
          scale={2.21}
        >
          <group
            name="cuplid02_tall"
            position={[1.37, 4.92, 1.39]}
            scale={[-0.03, 0.03, 0.03]}
          >
            <mesh
              name="Out"
              geometry={nodes.Out.geometry}
              material={materials.Cover}
              castShadow
              receiveShadow
              position={[70, 171, 60.41]}
              rotation={[0, 0, -Math.PI]}
              scale={[1.4 * 2.1, 1.4 * 0.66, 1.4 * 2.1]}
            />
          </group>
          <group name="cup_tall" position={[1.44, -1.14, 1.45]} scale={0.03}>
            <mesh
              name="Cup"
              geometry={nodes.Cup.geometry}
              material={materials.Paper}
              castShadow
              receiveShadow
              position={[-74.61, 120.02, 63.37]}
              rotation={[-Math.PI / 2, 0, -0.01]}
              scale={[1.18, 1.18, 0.85]}
            />
          </group>
        </group>
        <group
          name="Coffee cup"
          position={[11.88, 421.92, -290.97]}
          scale={2.21}
        >
          <group
            name="Text 2"
            position={[-1.92, -0.18, 2.31]}
            rotation={[0, -1.16, 0]}
            scale={0.45}
          >
            <mesh
              name="U"
              geometry={nodes.U.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-9.96, 1.45, -2.15]}
              rotation={[0, -1, 0]}
            />
            <mesh
              name="n"
              geometry={nodes.n.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-8.51, 1.45, 0.09]}
              rotation={[0, -0.66, 0]}
            />
            <mesh
              name="i"
              geometry={nodes.i.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-6.5, 1.45, 1.76]}
              rotation={[0, -0.32, 0]}
            />
            <mesh
              name="i1"
              geometry={nodes.i1.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-6.71, 1.45, 1.69]}
              rotation={[0, -0.32, 0]}
            />
            <mesh
              name="v"
              geometry={nodes.v.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-4.31, 1.45, 2.75]}
            />
            <mesh
              name="e"
              geometry={nodes.e.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-1.52, 1.45, 2.8]}
              rotation={[0, 0.17, 0]}
            />
            <mesh
              name="r"
              geometry={nodes.r.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[1.31, 1.45, 2.16]}
              rotation={[0, 0.54, 0]}
            />
            <mesh
              name="s"
              geometry={nodes.s.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[3.85, 1.45, 0.91]}
              rotation={[0, 1.01, 0]}
            />
            <mesh
              name="i2"
              geometry={nodes.i2.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[5.24, 1.45, -1.15]}
              rotation={[0, 1.08, 0]}
            />
            <mesh
              name="i3"
              geometry={nodes.i3.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[5.24, 1.45, -1.15]}
              rotation={[0, 1.08, 0]}
            />
            <mesh
              name="t"
              geometry={nodes.t.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[6.17, 1.45, -3.31]}
              rotation={[0, 1.27, 0]}
            />
            <mesh
              name="y"
              geometry={nodes.y.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[6.72, 1.45, -5.7]}
              rotation={[-Math.PI, 1.5, -Math.PI]}
            />
            <mesh
              name="o"
              geometry={nodes.o.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-10, -3.05, -2.21]}
              rotation={[0, -0.91, 0]}
            />
            <mesh
              name="f"
              geometry={nodes.f.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-8.52, -3.05, -0.26]}
              rotation={[0, -0.7, 0]}
            />
            <mesh
              name="T"
              geometry={nodes.T.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-6.22, -3.05, 1.7]}
              rotation={[0, -0.26, 0]}
            />
            <mesh
              name="o1"
              geometry={nodes.o1.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-4.04, -3.05, 2.44]}
              rotation={[0, -0.04, 0]}
            />
            <mesh
              name="r1"
              geometry={nodes.r1.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-1.32, -3.05, 2.59]}
              rotation={[0, 0.25, 0]}
            />
            <mesh
              name="o2"
              geometry={nodes.o2.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[1.18, -3.05, 2.09]}
              rotation={[0, 0.57, 0]}
            />
            <mesh
              name="n1"
              geometry={nodes.n1.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[3.5, -3.05, 0.74]}
              rotation={[0, 0.89, 0]}
            />
            <mesh
              name="t1"
              geometry={nodes.t1.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[5.17, -3.05, -1.16]}
              rotation={[0, 1.07, 0]}
            />
            <mesh
              name="o3"
              geometry={nodes.o3.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[6.35, -3.05, -3.36]}
              rotation={[0, 1.35, 0]}
            />
          </group>
          <mesh
            name="Cylinder 2"
            geometry={nodes["Cylinder 2"].geometry}
            material={materials.Coffee}
            castShadow
            receiveShadow
            position={[-0.48, -0.02, -3.65]}
            rotation={[Math.PI, 0.56, -Math.PI]}
            scale={[1.11, 1, 1.33]}
          />
          <mesh
            name="Boolean"
            geometry={nodes.Boolean.geometry}
            material={materials["Boolean Material"]}
            castShadow
            receiveShadow
            position={[3.09, 0.28, -3.77]}
          >
            <mesh
              name="Ellipse 2"
              geometry={nodes["Ellipse 2"].geometry}
              material={materials["Coffee cup"]}
              visible={false}
              castShadow
              receiveShadow
              position={[0.26, 0.41, -0.96]}
              scale={[0.87, 1.44, 1.92]}
            />
            <mesh
              name="Ellipse"
              geometry={nodes.Ellipse.geometry}
              material={materials["Coffee cup"]}
              visible={false}
              castShadow
              receiveShadow
              position={[0.26, 0.41, -0.5]}
              scale={[1.07, 1.75, 1]}
            />
          </mesh>
          <mesh
            name="Cylinder"
            geometry={nodes.Cylinder.geometry}
            material={materials["Coffee cup"]}
            castShadow
            receiveShadow
            position={[-0.5, 0.15, -3.64]}
            rotation={[-Math.PI, 0.56, Math.PI]}
          />
        </group>
        <mesh
          name="Track pad"
          geometry={nodes["Track pad"].geometry}
          material={materials.industrial}
          castShadow
          receiveShadow
          position={[36.32, 412.4, -252.89]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[1.52, 1.24, 0.09]}
        />
        <mesh
          name="Keyboard Rest"
          geometry={nodes["Keyboard Rest"].geometry}
          material={materials["Keyboard Rest Material"]}
          castShadow
          receiveShadow
          position={[-88.86, 413.8, -259.8]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[2.71, 3.2, 0.58]}
        />
        <mesh
          name="Keyboard"
          geometry={nodes.Keyboard.geometry}
          material={materials.Keyboard}
          castShadow
          receiveShadow
          position={[-45.18, 414.62, -253.41]}
          rotation={[1.68, 0, -Math.PI]}
          scale={[-1.34, 1.2, 0.05]}
        />
      </group>
    </>
  );
}
