/*
  Auto-generated by Spline
*/

import useSpline from "@splinetool/r3f-spline";

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline(
    "https://prod.spline.design/QYTJMMZaJ-SgDwox/scene.splinecode"
  );
  return (
    <>
      <group {...props} dispose={null}>
        <mesh
          name="Table"
          geometry={nodes.Table.geometry}
          material={materials["Table Material"]}
          castShadow
          receiveShadow
          position={[-47.56, 400, -289.65]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[2.03, 1.8, 1.14]}
        />
        <group name="White board" position={[238.63, 543.34, -341.09]}>
          <group
            name="Text"
            position={[5.18, 24.09, 5.86]}
            scale={[1.86, 1.29, 1.07]}
          >
            <mesh
              name="T"
              geometry={nodes.T.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-44.18, 15.4, 0]}
            />
            <mesh
              name="o"
              geometry={nodes.o.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-36.85, 15.4, 0]}
            />
            <mesh
              name="d"
              geometry={nodes.d.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-29.75, 15.4, 0]}
            />
            <mesh
              name="o1"
              geometry={nodes.o1.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-22.65, 15.4, 0]}
            />
            <mesh
              name="1"
              geometry={nodes["1"].geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-44.18, 1.9, 0]}
            />
            <mesh
              name="."
              geometry={nodes["."].geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-37.14, 1.9, 0]}
            />
            <mesh
              name="G"
              geometry={nodes.G.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-33.79, 1.9, 0]}
            />
            <mesh
              name="e"
              geometry={nodes.e.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-25.27, 1.9, 0]}
            />
            <mesh
              name="t"
              geometry={nodes.t.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-18.66, 1.9, 0]}
            />
            <mesh
              name="H"
              geometry={nodes.H.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-11.24, 1.9, 0]}
            />
            <mesh
              name="i"
              geometry={nodes.i.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-2.32, 1.9, 0]}
            />
            <mesh
              name="i1"
              geometry={nodes.i1.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-2.32, 1.9, 0]}
            />
            <mesh
              name="r"
              geometry={nodes.r.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[0.83, 1.9, 0]}
            />
            <mesh
              name="e1"
              geometry={nodes.e1.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[5.11, 1.9, 0]}
            />
            <mesh
              name="d1"
              geometry={nodes.d1.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[11.72, 1.9, 0]}
            />
            <mesh
              name="2"
              geometry={nodes["2"].geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-44.18, -11.6, 0]}
            />
            <mesh
              name=".1"
              geometry={nodes[".1"].geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-37.14, -11.6, 0]}
            />
            <mesh
              name="G1"
              geometry={nodes.G1.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-33.79, -11.6, 0]}
            />
            <mesh
              name="r1"
              geometry={nodes.r1.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-25.27, -11.6, 0]}
            />
            <mesh
              name="a"
              geometry={nodes.a.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-20.99, -11.6, 0]}
            />
            <mesh
              name="d2"
              geometry={nodes.d2.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-14.11, -11.6, 0]}
            />
            <mesh
              name="u"
              geometry={nodes.u.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-7.01, -11.6, 0]}
            />
            <mesh
              name="a1"
              geometry={nodes.a1.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[0.09, -11.6, 0]}
            />
            <mesh
              name="t1"
              geometry={nodes.t1.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[6.97, -11.6, 0]}
            />
            <mesh
              name="e2"
              geometry={nodes.e2.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[11.29, -11.6, 0]}
            />
            <mesh
              name="U"
              geometry={nodes.U.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-44.18, -25.1, 0]}
            />
            <mesh
              name="o2"
              geometry={nodes.o2.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-35.72, -25.1, 0]}
            />
            <mesh
              name="f"
              geometry={nodes.f.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-28.62, -25.1, 0]}
            />
            <mesh
              name="T1"
              geometry={nodes.T1.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-24.31, -25.1, 0]}
            />
          </group>
          <mesh
            name="White board1"
            geometry={nodes["White board1"].geometry}
            material={materials["White board1 Material"]}
            castShadow
            receiveShadow
            position={[3.35, 4.83, 3.27]}
            rotation={[Math.PI, 0, -Math.PI]}
            scale={[2.21, 2.21, 0.06]}
          />
          <mesh
            name="Cube 10"
            geometry={nodes["Cube 10"].geometry}
            material={materials["Cube 10 Material"]}
            castShadow
            receiveShadow
            position={[1.24, -87.97, 4.43]}
            rotation={[Math.PI, 0, -Math.PI]}
            scale={[2.21, 2.21, 0.09]}
          />
          <mesh
            name="Cube 8"
            geometry={nodes["Cube 8"].geometry}
            material={materials["Cube 8 Material"]}
            castShadow
            receiveShadow
            position={[0, 0, -3.03]}
            rotation={[Math.PI, 0, -Math.PI]}
            scale={[2.21, 1.85, 0.05]}
          />
        </group>
        <group
          name="Monitor"
          position={[-41.88, 575.7, -332.29]}
          scale={[1.79, 1.82, 2.21]}
        >
          <mesh
            name="Cube 2"
            geometry={nodes["Cube 2"].geometry}
            material={materials["Cube 2 Material"]}
            castShadow
            receiveShadow
            position={[0, 0.78, 2.75]}
            rotation={[-1.34, 0, 0]}
            scale={[0.62, 0.72, 0.29]}
          />
        </group>
        <group
          name="Monitor1"
          position={[-41.88, 501.48, -326.23]}
          scale={[2, 1.8, 1.2]}
        >
          <mesh
            name="Cube 3"
            geometry={nodes["Cube 3"].geometry}
            material={materials["Cube 3 Material"]}
            castShadow
            receiveShadow
            position={[0, -0.09, 3.07]}
            rotation={[-1.6, 0, 0]}
            scale={[0.75, 0.81, 0.28]}
          />
        </group>
        <mesh
          name="Cube"
          geometry={nodes.Cube.geometry}
          material={materials["Cube Material"]}
          castShadow
          receiveShadow
          position={[-230.66, 507.34, -316.08]}
          rotation={[Math.PI, 0, -Math.PI]}
          scale={[0.19, 0.98, 0.18]}
        />
        <mesh
          name="Cube1"
          geometry={nodes.Cube1.geometry}
          material={materials["Cube1 Material"]}
          castShadow
          receiveShadow
          position={[-230.66, 640.58, -316.08]}
          rotation={[Math.PI, 0, -Math.PI]}
          scale={[0.19, 0.98, 0.18]}
        />
        <mesh
          name="Cube2"
          geometry={nodes.Cube2.geometry}
          material={materials["Cube2 Material"]}
          castShadow
          receiveShadow
          position={[-307.36, 569.84, -316.08]}
          rotation={[Math.PI, 0, -Math.PI]}
          scale={[0.19, 0.98, 0.18]}
        />
        <mesh
          name="Cube3"
          geometry={nodes.Cube3.geometry}
          material={materials.white}
          castShadow
          receiveShadow
          position={[6.39, 717.62, -339]}
          rotation={[Math.PI, 0, -Math.PI]}
          scale={[-2.21, 0.98, 0.1]}
        />
        <mesh
          name="Wall"
          geometry={nodes.Wall.geometry}
          material={materials.Walls}
          castShadow
          receiveShadow
          position={[-4.67, 494.19, -392.22]}
          scale={[2.21, 1.88, 3.83]}
        />
        <group name="Github" position={[-231.08, 674.9, -294.75]} scale={6.39}>
          <mesh
            name="Shape 2"
            geometry={nodes["Shape 2"].geometry}
            material={materials.white}
            castShadow
            receiveShadow
            position={[-1.82, 1.93, -0.83]}
            scale={[0.85, 0.85, 1.31]}
          />
          <mesh
            name="Rectangle 17"
            geometry={nodes["Rectangle 17"].geometry}
            material={materials.Black}
            castShadow
            receiveShadow
            position={[-0.06, -0.83, -5.16]}
            scale={[0.03, 0.04, 0.15]}
          />
        </group>
        <group name="Mail" position={[-227.97, 541.75, -293.41]} scale={6.52}>
          <mesh
            name="Triangle 3"
            geometry={nodes["Triangle 3"].geometry}
            material={materials["Triangle 3 Material"]}
            castShadow
            receiveShadow
            position={[-0.06, -1.22, -0.16]}
            scale={[1.31, 1.37, 1.36]}
          />
          <mesh
            name="Triangle 2"
            geometry={nodes["Triangle 2"].geometry}
            material={materials["Triangle 2 Material"]}
            castShadow
            receiveShadow
            position={[-0.06, -0.3, -0.22]}
            rotation={[0, 0, Math.PI]}
            scale={[1.31, 1.37, 1.36]}
          />
          <mesh
            name="Rectangle 9"
            geometry={nodes["Rectangle 9"].geometry}
            material={materials["Rectangle 9 Material"]}
            castShadow
            receiveShadow
            position={[-0.07, -0.76, -0.74]}
            scale={0.92}
          />
          <mesh
            name="Rectangle 8"
            geometry={nodes["Rectangle 8"].geometry}
            material={materials["Rectangle 8 Material"]}
            castShadow
            receiveShadow
            position={[-0.07, -0.83, -0.9]}
            scale={1.1}
          />
          <mesh
            name="Rectangle 171"
            geometry={nodes["Rectangle 171"].geometry}
            material={materials["Rectangle 171 Material"]}
            castShadow
            receiveShadow
            position={[-0.06, -0.83, -5.09]}
            scale={[0.03, 0.04, 0.14]}
          />
        </group>
        <group
          name="Linkedin"
          position={[-307.36, 600.19, -303.08]}
          scale={6.52}
        >
          <mesh
            name="Rectangle 19"
            geometry={nodes["Rectangle 19"].geometry}
            material={materials.white}
            castShadow
            receiveShadow
            position={[0.23, -0.73, 0.29]}
            scale={[1.06, 1.06, 0.71]}
          />
          <mesh
            name="Rectangle 18"
            geometry={nodes["Rectangle 18"].geometry}
            material={materials.white}
            castShadow
            receiveShadow
            position={[-1.42, -0.77, 0.35]}
            scale={[1.06, 1.03, 0.72]}
          />
          <mesh
            name="Ellipse"
            geometry={nodes.Ellipse.geometry}
            material={materials.white}
            castShadow
            receiveShadow
            position={[-1.48, 1.96, 0.29]}
            scale={0.68}
          />
          <mesh
            name="Rectangle 172"
            geometry={nodes["Rectangle 172"].geometry}
            material={materials["Rectangle 172 Material"]}
            castShadow
            receiveShadow
            position={[0, -0.21, -3.67]}
            scale={[0.03, 0.04, 0.14]}
          />
        </group>
      </group>
    </>
  );
}
