/*
  Auto-generated by Spline
*/

import useSpline from "@splinetool/r3f-spline";

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline(
    "https://prod.spline.design/9Mwd37D1i9SOz0v4/scene.splinecode"
  );
  return (
    <>
      <group {...props} dispose={null}>
        <mesh
          name="Pillar"
          geometry={nodes.Pillar.geometry}
          material={materials.Walls}
          castShadow
          receiveShadow
          position={[-2.04, 329.62, 200.32]}
          scale={1.24}
        />
      </group>
    </>
  );
}
