/*
  Auto-generated by Spline
*/

import useSpline from "@splinetool/r3f-spline";

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline(
    "https://prod.spline.design/sR94417MaPswqRLm/scene.splinecode"
  );
  return (
    <>
      <color attach="background" args={["#4b4d52"]} />
      <group {...props} dispose={null}>
        <group
          name="Office Chair"
          position={[51.46, 263.75, -182.7]}
          scale={2.21}
        >
          <mesh
            name="Cylinder"
            geometry={nodes.Cylinder.geometry}
            material={materials["Chair Leg"]}
            castShadow
            receiveShadow
            position={[0.07, 8.58, 0.02]}
          />
          <mesh
            name="Merged Geometry"
            geometry={nodes["Merged Geometry"].geometry}
            material={materials["Merged Geometry Material"]}
            castShadow
            receiveShadow
            position={[0, -33.74, 0]}
            scale={0.45}
          />
          <mesh
            name="Merged Geometry 2"
            geometry={nodes["Merged Geometry 2"].geometry}
            material={materials["Merged Geometry 2 Material"]}
            castShadow
            receiveShadow
            position={[0.31, -26.76, 0.45]}
            scale={0.45}
          />
          <mesh
            name="Ellipse"
            geometry={nodes.Ellipse.geometry}
            material={materials["Ellipse Material"]}
            castShadow
            receiveShadow
            position={[-0.7, 33.86, 0.95]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.57, 0.57, 0.99]}
          />
        </group>
      </group>
    </>
  );
}
