/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: SunnyChen753/SW fan (https://sketchfab.com/sunnychen753)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/spacex-falcon-heavy-2f11453207944cedba00e2c6c1aa1269
title: SpaceX Falcon Heavy
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    process.env.PUBLIC_URL + "/falcon_heavy/scene.gltf"
  );
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={
            materials[
              "falcon_heavy_texture_bf32b81e-0ee7-4847-b2fd-4bccbc96dcaf"
            ]
          }
        />
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
