/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: KI NG (https://sketchfab.com/dadybandit)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/ultrawide-screen-046aeb9f891547f2bb96670b8ec7f83a
title: Ultrawide screen
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Monitor({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/ultrawide_screen/scene.gltf");
  return (
    <group ref={group} dispose={null}>
      <group>
        <group>
          <group {...props} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube001_black_0.geometry}
              material={materials.black}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube001_screen_0.geometry}
              material={materials.screen}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
