/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: pozo3d (https://sketchfab.com/pozo3d)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/folded-wrinkled-paper-9a1d10ebb9a241ffa37b6f6df4adc1f0
title: Folded Wrinkled Paper
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    process.env.PUBLIC_URL + "/paper/scene.gltf"
  );
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.blinn1SG}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
