/*
  Auto-generated by Spline
*/

import useSpline from "@splinetool/r3f-spline";

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline(
    "https://prod.spline.design/wTZxsAfPK16ndVQQ/scene.splinecode"
  );
  return (
    <>
      <color attach="background" args={["#4b4d52"]} />
      <group {...props} dispose={null}>
        <group
          name="Plant"
          position={[-278.26, 299.98, -200.3]}
          rotation={[0, 0.61, 0]}
          scale={2.12}
        >
          <mesh
            name="Merged Geometry"
            geometry={nodes["Merged Geometry"].geometry}
            material={materials.Leaf}
            castShadow
            receiveShadow
            position={[0, 16.87, 0]}
            scale={0.47}
          />
          <mesh
            name="Ellipse"
            geometry={nodes.Ellipse.geometry}
            material={materials.Dirt}
            castShadow
            receiveShadow
            position={[1.18, -17.94, 1.25]}
            rotation={[-Math.PI / 2, -0.02, 0]}
            scale={2.32}
          />
          <mesh
            name="Cylinder"
            geometry={nodes.Cylinder.geometry}
            material={materials.pot}
            castShadow
            receiveShadow
            position={[0.89, -28.92, 0.95]}
            scale={[1, 0.62, 1]}
          />
        </group>
        <group
          name="Plant1"
          position={[236.06, 299.98, -249.55]}
          rotation={[0, -1.02, 0]}
          scale={2.12}
        >
          <mesh
            name="Merged Geometry1"
            geometry={nodes["Merged Geometry1"].geometry}
            material={materials.Leaf}
            castShadow
            receiveShadow
            position={[0, 16.87, 0]}
            scale={0.47}
          />
          <mesh
            name="Ellipse1"
            geometry={nodes.Ellipse1.geometry}
            material={materials.Dirt}
            castShadow
            receiveShadow
            position={[1.18, -17.94, 1.25]}
            rotation={[-Math.PI / 2, -0.02, 0]}
            scale={2.32}
          />
          <mesh
            name="Cylinder1"
            geometry={nodes.Cylinder1.geometry}
            material={materials.pot}
            castShadow
            receiveShadow
            position={[0.89, -28.92, 0.95]}
            scale={[1, 0.62, 1]}
          />
        </group>
      </group>
    </>
  );
}
