/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Smoggybeard (https://sketchfab.com/Smoggybeard)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/toy-rocketship-94000688843242f79a44686d086663b0
title: Toy Rocketship
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Toy/scene.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            receiveShadow
            castShadow
            geometry={nodes.defaultMaterial.geometry}
            material={materials.Fire}
          />
          <mesh
            receiveShadow
            castShadow
            geometry={nodes.defaultMaterial_1.geometry}
            material={materials.Blue_Plastic}
          />
          <mesh
            receiveShadow
            castShadow
            geometry={nodes.defaultMaterial_2.geometry}
            material={materials.DarkGrey_Plastic}
          />
          <mesh
            receiveShadow
            castShadow
            geometry={nodes.defaultMaterial_3.geometry}
            material={materials.Chrome}
          />
          <mesh
            receiveShadow
            castShadow
            geometry={nodes.defaultMaterial_4.geometry}
            material={materials.Red_Plastic}
          />
          <mesh
            receiveShadow
            castShadow
            geometry={nodes.defaultMaterial_5.geometry}
            material={materials.White_Plastic}
          />
          <mesh
            receiveShadow
            castShadow
            geometry={nodes.defaultMaterial_6.geometry}
            material={materials.Stand_Brass}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
