/*
  Auto-generated by Spline
*/

import useSpline from "@splinetool/r3f-spline";
import { OrthographicCamera } from "@react-three/drei";

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline(
    "https://prod.spline.design/fSjyJzWPteAvz2w8/scene.splinecode"
  );
  return (
    <>
      <group {...props} dispose={null}>
        <group
          name="Window Table"
          position={[-266.42, 291.27, 9.39]}
          scale={[2.23, 2.21, 2.21]}
        >
          <mesh
            name="Cube 16"
            geometry={nodes["Cube 16"].geometry}
            material={materials.Keyboard}
            castShadow
            receiveShadow
            position={[0, 56.39, 0.24]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[1.65, 2.71, 0.19]}
          />
          <mesh
            name="Rectangle 4"
            geometry={nodes["Rectangle 4"].geometry}
            material={materials.T}
            castShadow
            receiveShadow
            position={[0, -53.28, 0.24]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            name="Cylinder"
            geometry={nodes.Cylinder.geometry}
            material={materials.T}
            castShadow
            receiveShadow
            position={[0, -3.77, 0]}
            scale={[1, 11.32, 1]}
          />
        </group>
        <group
          name="Chair"
          position={[-164.24, 256.39, -32.59]}
          scale={[2.23, 2.21, 2.21]}
        >
          <mesh
            name="Cube 161"
            geometry={nodes["Cube 161"].geometry}
            material={materials["Chair top"]}
            castShadow
            receiveShadow
            position={[0.01, 34.28, -0.49]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.96, 1.58, 0.11]}
          />
          <mesh
            name="Rectangle 5"
            geometry={nodes["Rectangle 5"].geometry}
            material={materials.T}
            castShadow
            receiveShadow
            position={[0, -36.15, 0.17]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.7, 0.7, 0.68]}
          />
          <mesh
            name="Cylinder 2"
            geometry={nodes["Cylinder 2"].geometry}
            material={materials.T}
            castShadow
            receiveShadow
            position={[0, -2.57, 0]}
            scale={[0.7, 7.72, 0.7]}
          />
        </group>
        <group
          name="Chair1"
          position={[-255.91, 253.63, 119.31]}
          scale={[2.23, 2.21, 2.21]}
        >
          <mesh
            name="Cube 17"
            geometry={nodes["Cube 17"].geometry}
            material={materials["Chair top"]}
            castShadow
            receiveShadow
            position={[-0.42, 43.51, -0.04]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.96, 1.58, 0.11]}
          />
          <mesh
            name="Rectangle 51"
            geometry={nodes["Rectangle 51"].geometry}
            material={materials.T}
            castShadow
            receiveShadow
            position={[0, -36.46, 0.17]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.7, 0.7, 0.68]}
          />
          <mesh
            name="Cylinder 21"
            geometry={nodes["Cylinder 21"].geometry}
            material={materials.T}
            castShadow
            receiveShadow
            position={[0, 0.81, 0]}
            scale={[0.7, 8.15, 0.7]}
          />
        </group>
        <group
          name="Coffee cup"
          position={[-273.22, 434.57, 38.24]}
          rotation={[0, -0.4, 0]}
          scale={2.21}
        >
          <group
            name="Text 2"
            position={[-1.92, -0.18, 2.31]}
            rotation={[0, -1.16, 0]}
            scale={0.45}
          >
            <mesh
              name="U"
              geometry={nodes.U.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-9.96, 1.45, -2.15]}
              rotation={[0, -1, 0]}
            />
            <mesh
              name="n"
              geometry={nodes.n.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-8.51, 1.45, 0.09]}
              rotation={[0, -0.66, 0]}
            />
            <mesh
              name="i"
              geometry={nodes.i.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-6.5, 1.45, 1.76]}
              rotation={[0, -0.32, 0]}
            />
            <mesh
              name="i1"
              geometry={nodes.i1.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-6.71, 1.45, 1.69]}
              rotation={[0, -0.32, 0]}
            />
            <mesh
              name="v"
              geometry={nodes.v.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-4.31, 1.45, 2.75]}
            />
            <mesh
              name="e"
              geometry={nodes.e.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-1.52, 1.45, 2.8]}
              rotation={[0, 0.17, 0]}
            />
            <mesh
              name="r"
              geometry={nodes.r.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[1.31, 1.45, 2.16]}
              rotation={[0, 0.54, 0]}
            />
            <mesh
              name="s"
              geometry={nodes.s.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[3.85, 1.45, 0.91]}
              rotation={[0, 1.01, 0]}
            />
            <mesh
              name="i2"
              geometry={nodes.i2.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[5.24, 1.45, -1.15]}
              rotation={[0, 1.08, 0]}
            />
            <mesh
              name="i3"
              geometry={nodes.i3.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[5.24, 1.45, -1.15]}
              rotation={[0, 1.08, 0]}
            />
            <mesh
              name="t"
              geometry={nodes.t.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[6.17, 1.45, -3.31]}
              rotation={[0, 1.27, 0]}
            />
            <mesh
              name="y"
              geometry={nodes.y.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[6.72, 1.45, -5.7]}
              rotation={[-Math.PI, 1.5, -Math.PI]}
            />
            <mesh
              name="o"
              geometry={nodes.o.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-10, -3.05, -2.21]}
              rotation={[0, -0.91, 0]}
            />
            <mesh
              name="f"
              geometry={nodes.f.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-8.52, -3.05, -0.26]}
              rotation={[0, -0.7, 0]}
            />
            <mesh
              name="T"
              geometry={nodes.T.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-6.22, -3.05, 1.7]}
              rotation={[0, -0.26, 0]}
            />
            <mesh
              name="o1"
              geometry={nodes.o1.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-4.04, -3.05, 2.44]}
              rotation={[0, -0.04, 0]}
            />
            <mesh
              name="r1"
              geometry={nodes.r1.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-1.32, -3.05, 2.59]}
              rotation={[0, 0.25, 0]}
            />
            <mesh
              name="o2"
              geometry={nodes.o2.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[1.18, -3.05, 2.09]}
              rotation={[0, 0.57, 0]}
            />
            <mesh
              name="n1"
              geometry={nodes.n1.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[3.5, -3.05, 0.74]}
              rotation={[0, 0.89, 0]}
            />
            <mesh
              name="t1"
              geometry={nodes.t1.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[5.17, -3.05, -1.16]}
              rotation={[0, 1.07, 0]}
            />
            <mesh
              name="o3"
              geometry={nodes.o3.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[6.35, -3.05, -3.36]}
              rotation={[0, 1.35, 0]}
            />
          </group>
          <mesh
            name="Cylinder 22"
            geometry={nodes["Cylinder 22"].geometry}
            material={materials.Coffee}
            castShadow
            receiveShadow
            position={[-0.48, -0.02, -3.65]}
            rotation={[Math.PI, 0.56, -Math.PI]}
            scale={[1.11, 1, 1.33]}
          />
          <mesh
            name="Boolean"
            geometry={nodes.Boolean.geometry}
            material={materials["Boolean Material"]}
            castShadow
            receiveShadow
            position={[3.09, 0.28, -3.77]}
          >
            <mesh
              name="Ellipse 2"
              geometry={nodes["Ellipse 2"].geometry}
              material={materials["Ellipse 2 Material"]}
              visible={false}
              castShadow
              receiveShadow
              position={[0.29, 0.41, -0.96]}
              scale={[0.87, 1.44, 1.92]}
            />
            <mesh
              name="Ellipse"
              geometry={nodes.Ellipse.geometry}
              material={materials["Coffee cup"]}
              visible={false}
              castShadow
              receiveShadow
              position={[0.26, 0.41, -0.5]}
              scale={[1.07, 1.75, 1]}
            />
          </mesh>
          <mesh
            name="Cylinder1"
            geometry={nodes.Cylinder1.geometry}
            material={materials["Coffee cup"]}
            castShadow
            receiveShadow
            position={[-0.5, 0.15, -3.64]}
            rotation={[-Math.PI, 0.56, Math.PI]}
          />
        </group>
        <group
          name="Coffee cup1"
          position={[-217.82, 434.57, -8.53]}
          rotation={[0, 1.16, 0]}
          scale={2.21}
        >
          <group
            name="Text 21"
            position={[-1.92, -0.18, 2.31]}
            rotation={[0, -1.16, 0]}
            scale={0.45}
          >
            <mesh
              name="U1"
              geometry={nodes.U1.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-9.96, 1.45, -2.15]}
              rotation={[0, -1, 0]}
            />
            <mesh
              name="n2"
              geometry={nodes.n2.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-8.51, 1.45, 0.09]}
              rotation={[0, -0.66, 0]}
            />
            <mesh
              name="i4"
              geometry={nodes.i4.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-6.5, 1.45, 1.76]}
              rotation={[0, -0.32, 0]}
            />
            <mesh
              name="i5"
              geometry={nodes.i5.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-6.71, 1.45, 1.69]}
              rotation={[0, -0.32, 0]}
            />
            <mesh
              name="v1"
              geometry={nodes.v1.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-4.31, 1.45, 2.75]}
            />
            <mesh
              name="e1"
              geometry={nodes.e1.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-1.52, 1.45, 2.8]}
              rotation={[0, 0.17, 0]}
            />
            <mesh
              name="r2"
              geometry={nodes.r2.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[1.31, 1.45, 2.16]}
              rotation={[0, 0.54, 0]}
            />
            <mesh
              name="s1"
              geometry={nodes.s1.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[3.85, 1.45, 0.91]}
              rotation={[0, 1.01, 0]}
            />
            <mesh
              name="i6"
              geometry={nodes.i6.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[5.24, 1.45, -1.15]}
              rotation={[0, 1.08, 0]}
            />
            <mesh
              name="i7"
              geometry={nodes.i7.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[5.24, 1.45, -1.15]}
              rotation={[0, 1.08, 0]}
            />
            <mesh
              name="t2"
              geometry={nodes.t2.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[6.17, 1.45, -3.31]}
              rotation={[0, 1.27, 0]}
            />
            <mesh
              name="y1"
              geometry={nodes.y1.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[6.72, 1.45, -5.7]}
              rotation={[-Math.PI, 1.5, -Math.PI]}
            />
            <mesh
              name="o4"
              geometry={nodes.o4.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-10, -3.05, -2.21]}
              rotation={[0, -0.91, 0]}
            />
            <mesh
              name="f1"
              geometry={nodes.f1.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-8.52, -3.05, -0.26]}
              rotation={[0, -0.7, 0]}
            />
            <mesh
              name="T1"
              geometry={nodes.T1.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-6.22, -3.05, 1.7]}
              rotation={[0, -0.26, 0]}
            />
            <mesh
              name="o5"
              geometry={nodes.o5.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-4.04, -3.05, 2.44]}
              rotation={[0, -0.04, 0]}
            />
            <mesh
              name="r3"
              geometry={nodes.r3.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[-1.32, -3.05, 2.59]}
              rotation={[0, 0.25, 0]}
            />
            <mesh
              name="o6"
              geometry={nodes.o6.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[1.18, -3.05, 2.09]}
              rotation={[0, 0.57, 0]}
            />
            <mesh
              name="n3"
              geometry={nodes.n3.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[3.5, -3.05, 0.74]}
              rotation={[0, 0.89, 0]}
            />
            <mesh
              name="t3"
              geometry={nodes.t3.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[5.17, -3.05, -1.16]}
              rotation={[0, 1.07, 0]}
            />
            <mesh
              name="o7"
              geometry={nodes.o7.geometry}
              material={materials["My Text Material"]}
              castShadow
              receiveShadow
              position={[6.35, -3.05, -3.36]}
              rotation={[0, 1.35, 0]}
            />
          </group>
          <mesh
            name="Cylinder 23"
            geometry={nodes["Cylinder 23"].geometry}
            material={materials.Coffee}
            castShadow
            receiveShadow
            position={[-0.48, -0.02, -3.65]}
            rotation={[Math.PI, 0.56, -Math.PI]}
            scale={[1.11, 1, 1.33]}
          />
          <mesh
            name="Boolean1"
            geometry={nodes.Boolean1.geometry}
            material={materials["Boolean1 Material"]}
            castShadow
            receiveShadow
            position={[3.09, 0.28, -3.77]}
          >
            <mesh
              name="Ellipse 21"
              geometry={nodes["Ellipse 21"].geometry}
              material={materials["Ellipse 21 Material"]}
              visible={false}
              castShadow
              receiveShadow
              position={[0.29, 0.41, -0.96]}
              scale={[0.87, 1.44, 1.92]}
            />
            <mesh
              name="Ellipse1"
              geometry={nodes.Ellipse1.geometry}
              material={materials["Coffee cup"]}
              visible={false}
              castShadow
              receiveShadow
              position={[0.26, 0.41, -0.5]}
              scale={[1.07, 1.75, 1]}
            />
          </mesh>
          <mesh
            name="Cylinder2"
            geometry={nodes.Cylinder2.geometry}
            material={materials["Coffee cup"]}
            castShadow
            receiveShadow
            position={[-0.5, 0.15, -3.64]}
            rotation={[-Math.PI, 0.56, Math.PI]}
          />
        </group>
      </group>
    </>
  );
}
